export type AreaEntry =
  | { type: 'AdministrativeArea'; name: string }
  | { type: 'City'; name: string };

export const AREA_SERVED: AreaEntry[] = [
  { type: 'AdministrativeArea', name: '神奈川県' },
  { type: 'City', name: '横浜市' },
  { type: 'City', name: '横浜市鶴見区' },
  { type: 'City', name: '横浜市神奈川区' },
  { type: 'City', name: '横浜市西区' },
  { type: 'City', name: '横浜市中区' },
  { type: 'City', name: '横浜市南区' },
  { type: 'City', name: '横浜市港南区' },
  { type: 'City', name: '横浜市保土ケ谷区' },
  { type: 'City', name: '横浜市旭区' },
  { type: 'City', name: '横浜市磯子区' },
  { type: 'City', name: '横浜市金沢区' },
  { type: 'City', name: '横浜市港北区' },
  { type: 'City', name: '横浜市緑区' },
  { type: 'City', name: '横浜市青葉区' },
  { type: 'City', name: '横浜市都筑区' },
  { type: 'City', name: '横浜市戸塚区' },
  { type: 'City', name: '横浜市栄区' },
  { type: 'City', name: '横浜市泉区' },
  { type: 'City', name: '横浜市瀬谷区' },
  { type: 'City', name: '川崎市' },
  { type: 'City', name: '相模原市' },
  { type: 'City', name: '横須賀市' },
  { type: 'City', name: '平塚市' },
  { type: 'City', name: '鎌倉市' },
  { type: 'City', name: '藤沢市' },
  { type: 'City', name: '小田原市' },
  { type: 'City', name: '茅ヶ崎市' },
  { type: 'City', name: '逗子市' },
  { type: 'City', name: '三浦市' },
  { type: 'City', name: '秦野市' },
  { type: 'City', name: '厚木市' },
  { type: 'City', name: '大和市' },
  { type: 'City', name: '伊勢原市' },
  { type: 'City', name: '海老名市' },
  { type: 'City', name: '座間市' },
  { type: 'City', name: '南足柄市' },
  { type: 'City', name: '綾瀬市' },
  { type: 'City', name: '葉山町' },
  { type: 'City', name: '寒川町' },
  { type: 'City', name: '大磯町' },
  { type: 'City', name: '二宮町' },
  { type: 'City', name: '中井町' },
  { type: 'City', name: '大井町' },
  { type: 'City', name: '松田町' },
  { type: 'City', name: '山北町' },
  { type: 'City', name: '開成町' },
  { type: 'City', name: '箱根町' },
  { type: 'City', name: '真鶴町' },
  { type: 'City', name: '湯河原町' },
  { type: 'City', name: '愛川町' },
  { type: 'City', name: '清川村' },
];

export const AREA_SERVED_JSON_LD = AREA_SERVED.map((a) => ({
  '@type': a.type,
  name: a.name,
}));

// --- ページ表示用の単一ソース ---
// エリア一覧ページ (area-yokohama / area-kawasaki / area-kanagawa 等) はここを import して使う。
// AREA_SERVED (JSON-LD用) と同一の対応エリアを、表示しやすい形で持つ。

/** 横浜市の全18区 */
export const YOKOHAMA_WARDS: string[] = [
  '鶴見区',
  '神奈川区',
  '西区',
  '中区',
  '南区',
  '港南区',
  '保土ケ谷区',
  '旭区',
  '磯子区',
  '金沢区',
  '港北区',
  '緑区',
  '青葉区',
  '都筑区',
  '戸塚区',
  '栄区',
  '泉区',
  '瀬谷区',
];

/** 横浜市を除く神奈川県内の対応市町村（市部 + 郡部） */
export const KANAGAWA_MUNICIPALITIES: string[] = [
  '川崎市',
  '相模原市',
  '藤沢市',
  '横須賀市',
  '平塚市',
  '厚木市',
  '大和市',
  '茅ヶ崎市',
  '小田原市',
  '鎌倉市',
  '秦野市',
  '海老名市',
  '座間市',
  '伊勢原市',
  '綾瀬市',
  '逗子市',
  '三浦市',
  '南足柄市',
  '葉山町',
  '寒川町',
  '大磯町',
  '二宮町',
  '中井町',
  '大井町',
  '松田町',
  '山北町',
  '開成町',
  '箱根町',
  '真鶴町',
  '湯河原町',
  '愛川町',
  '清川村',
];
